# Generated by Django 5.0.4 on 2024-04-27 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game",
                    models.CharField(
                        choices=[
                            ("RLT", "Roulette"),
                            ("BKJ", "Blackjack"),
                            ("BAC", "Baccarat"),
                            ("SLT", "Slots"),
                            ("CPS", "Craps"),
                            ("PKR", "Poker"),
                            ("SPT", "Sports"),
                            ("OTH", "Other"),
                        ],
                        default="SPT",
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("decimal_odds", models.DecimalField(decimal_places=2, max_digits=8)),
                ("win", models.BooleanField(default=False)),
                ("profit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("bet_date", models.DateField(default=datetime.date(2024, 4, 27))),
            ],
        ),
    ]
