# Generated by Django 5.0.4 on 2024-04-27 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="bet_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 4, 27, 10, 7, 5, 320262, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
