# Generated by Django 5.0.4 on 2024-04-27 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_alter_bet_bet_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="bet_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
